s3s-aws: proxy: improve readability
Nugine/s3s pull request #123
Opened 2024-01-08 08:49 UTC by nomick

The patch simplifies header generation in the proxy component to improve the readability of the generated code. This may also be found useful if one writes a custom proxy with more logic.

---

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-01-11 10:33 UTC, Nugine requested changes

2024-01-11 10:33 UTC, Nugine commented on crates/s3s/src/response.rs
> +    }
I prefer the following order and style
1. the major constructor `new`, and then additional constructors `with_*`
2. a blank line between each method
3. trivial constructors do not depend on each other

```rust
    pub fn new(output: T) -> Self {
        Self {
            output,
            headers: HeaderMap::new(),
            extensions: Extensions::new(),
        }
    }

    pub fn with_headers(output: T, headers: HeaderMap<HeaderValue>) -> Self {
        Self {
            output,
            headers,
            extensions: Extensions::new(),
        }
    }
```

2024-01-11 10:33 UTC, Nugine commented on crates/s3s-aws/src/proxy/meta.rs
> +use hyper::{header::HeaderValue, HeaderMap};
Imports are grouped by modules

```rust
use s3s::header::{X_AMZ_ID_2, X_AMZ_REQUEST_ID};
use s3s::{s3_error, S3Result};

use aws_sdk_s3::operation::{RequestId, RequestIdExt};
use hyper::header::HeaderValue;
use hyper::HeaderMap;
```

2024-01-11 13:42 UTC, nomick commented on crates/s3s-aws/src/proxy/meta.rs
> +use hyper::{header::HeaderValue, HeaderMap};
thanks.

2024-01-12 05:56 UTC, Nugine approved these changes

2024-01-12 06:27 UTC, merged