Expose Error Serialization To Consumers to Allow Ergnomoic Middleware
Nugine/s3s pull request #157
Opened 2024-07-18 10:45 UTC by Eosis

## Description

As part of work I have done recently to prevent un-bounded memory growth in s3s, I put a basic middleware in front of my service that checks the signature mechanism and content-length, denying requests that will incur massive memory usage.

In doing this, I realized I would need to write my own serialization to send the error response using Hyper. This PR exposes the internal `serialize_error` method so it can used in consumer's middleware.

I was not quite sure how you would prefer this to be exposed / if you think this is a good idea at all. Let me know your thoughts / suggestions.

```rust

impl Service<hyper::Request<hyper::body::Incoming>> for PreCheck {
    type Response = hyper::Response<Body>;

    type Error = S3Error;

    type Future = BoxFuture<'static, Result<Self::Response, Self::Error>>;

    fn call(&self, req: Req) -> Self::Future {
        if (some_check_on_req(req)) {
            // Handle the request as normal
            return self.inner.call(req);
        }
    
        // Oh Dear, I don't want to handle this one!
        let response = s3s::serialize_error(s3_error!(
            AccountProblem,
            "You ain't paid your bills!"
        ), true).map(Into::into);

         Box::pin(
            future::ready(
                response
            )
         )
    }
}
```

## Caveats

This is currently built atop the PR I opened earlier, #156 .

---

*By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.*

2024-07-18 12:45 UTC, Eosis commented
CI Failure seems to be related to how I have exposed this. I will wait for general feedback on the PR before I dive into fixing that.

2024-08-04 09:53 UTC, Nugine requested changes
It is a missing part in our public API. We need to expose the conversion from `S3Error` to `hyper::Response<Body>`. Note that `crate::http::Response` is an internal type.

It can be a method of `S3Error` named `to_hyper`, or other better names. A top-level function may be confusing.

The default serialization is XML with declaration. The `no_decl` option may be useless for users in most cases. We can hide it for now.

2024-08-08 09:46 UTC, Eosis commented
I've switched to using a method on the S3Error type rather than exposing it at the top level. Let me know what you think. :+1:

2024-08-08 11:02 UTC, Nugine approved these changes
LGTM

2024-08-08 11:02 UTC, merged